config/routes.rb
Rails.application.routes.draw do
  get 'songs/index'

  get 'songs/upload'

  get 'songs/delete'

  match "songs/upload",:via => [:post], :as => "upload"
match "songs/delete",:via => [:get], :as => "delete"
  match "/share" => "songs#index", via: [:get]

  
  devise_for :users
  resources :posts do
  	member do
  		get "like", to: "posts#upvote"
  		get "dislike", to: "posts#downvote"
  	end
  	resources :comments
	end
  root 'posts#index'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :post
  belongs_to :user
end

app/models/post.rb
class Post < ActiveRecord::Base
	acts_as_votable
	belongs_to :user
	has_many :comments
	has_attached_file :image, styles: { medium: "700x500#", small: "350x250#" }
  validates_attachment_content_type :image, content_type: /\Aimage\/.*\Z/
  
  def self.search(search)
  if search
    Post.find(:all, :conditions => ['name LIKE ?', "%#{search}%"])
  else
   
  end
end
  
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
  has_many :posts
  has_many :comments
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
 

   http_basic_authenticate_with name: "dhh", password: "secret"
  protect_from_forgery with: :exception

  before_filter :configure_permitted_parameters, if: :devise_controller?

	protected

	def configure_permitted_parameters
	  devise_parameter_sanitizer.for(:sign_up) << :name
	  devise_parameter_sanitizer.for(:account_update) << :name
	end
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController
	before_action :authenticate_user!
	def create
		@post = Post.find(params[:post_id])
		@comment = Comment.create(params[:comment].permit(:content))
		@comment.user_id = current_user.id
		@comment.post_id = @post.id

		if @comment.save
			redirect_to post_path(@post)
		else
			render 'new'
		end
	end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
	before_action :find_post, only: [:show, :edit, :update, :destroy, :upvote, :downvote]
	before_action :authenticate_user!, except: [:index, :show]

	def index
		@posts = Post.all.order("created_at DESC")
    @post = Post.search(params[:search])
	end

	def show
		@comments = Comment.where(post_id: @post)
		@random_post = Post.where.not(id: @post).order("RANDOM()").first

	end

	def new
		@post = current_user.posts.build
	end

	def create
		@post = current_user.posts.build(post_params)

		if @post.save
			redirect_to @post
		else
			render 'new'
		end
	end

	def edit
	end

	def update
		if @post.update(post_params)
			redirect_to @post
		else
			render 'edit'
		end
	end

	def destroy
		@post.destroy
		redirect_to root_path
	end

	def upvote
		@post.upvote_by current_user
		redirect_to :back
	end

	def downvote
		@post.downvote_from current_user
		redirect_to :back
	end

	private

	def find_post
		@post = Post.find(params[:id])
	end

	def post_params
		params.require(:post).permit(:title, :link, :description, :image)
	end
end

app/controllers/songs_controller.rb
class SongsController < ApplicationController
  include AWS::S3
  def index
    @songs = AWS::S3::Bucket.find('apiapi').objects
  end
 
  def upload
    begin
      AWS::S3::S3Object.store(sanitize_filename(params[:mp3file].original_filename), params[:mp3file].read, 'apiapi', :access => :public_read)
      redirect_to "/share"
    rescue
      render :text => "Couldn't complete the upload"
    end
  end
 
  def delete
    if (params[:song])
      AWS::S3::S3Object.find(params[:song], 'apiapi').delete
      redirect_to root_path
    else
      render :text => "No song was found to delete!"
    end
  end
  private
 
  def sanitize_filename(file_name)
    just_filename = File.basename(file_name)
    just_filename.sub(/[^\w\.\-]/,'_')
  end
 
end

app/helpers/application_helper.rb
module ApplicationHelper
  def download_url_for(song_key)
    AWS::S3::S3Object.url_for(song_key, 'apiapi', :authenticated => false)
end
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/songs_helper.rb
module SongsHelper
end

app/views/comments/_form.html.erb
<%= simple_form_for([@post, @post.comments.build]) do |f| %>
  <%= f.input :content, label: "Reply to thread" %>
  <%= f.button :submit, class: "button" %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html>
<head>
  <title> Tag It </title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
 <!-- <link href="http://cdnjs.cloudflare.com/ajax/libs/normalize/3.0.1/normalize.min.css" rel="stylesheet">-->
  <link href="http://maxcdn.bootstrapcdn.com/font-awesome/4.2.0/css/font-awesome.min.css" rel="stylesheet">
  <%= csrf_meta_tags %>
</head>
<body>

 
  <!--<video class="sleep-video" autoplay loop>
    <source src="https://s3.amazonaws.com/apiapi/bg.mp4">

</video>-->

  
  
  <nav class="navbar navbar-default" style="">
  <div class="container">
    <div class="navbar-brand" id="logo">
      <%= link_to "Inspire" ,root_path, id: "logo" %>
    </div>
    
    <ul class="nav navbar-nav navbar-right">
    	<li class="fb"><a href="https://www.facebook.com/IndieGala?fref=ts" 		title="Visit our Facebook page" 		target="_blank"><i class="fa fa-facebook">			</i></a></li>
							<li class="tw"><a href="https://twitter.com/IndieGala" 						title="Visit our Twitter page" 			target="_blank"><i class="fa fa-twitter">			</i></a></li>
							<li class="yt"><a href="https://www.youtube.com/user/IndieGala" 			title="Visit our Youtube channel" 		target="_blank"><i class="fa fa-youtube-play">		</i></a></li>
							<li class="gp"><a href="https://plus.google.com/u/0/106638160915246664250/about" 			title="Visit our Google+ page" 		target="_blank"><i class="fa fa-google-plus"></i></a></li>
							<li class="st"><a href="https://steamcommunity.com/groups/indiegala" 		title="Visit our Steam page" 			target="_blank"> <!-- <img src="/img/icons/steam-icon-w.png" /> <!-- <i class="fa fa-steam"></i> --></a></li>
						</ul>

    
    
    <% if user_signed_in? %>
      <ul class="nav navbar-nav navbar-right">
        <li>
         <%= link_to current_user.name, edit_user_registration_path %>
        </li>
        <li>
          <%= link_to "Add New Inspiration/Interest", new_post_path, class: "button", id: "logo" %>
        </li>
        <li>
          <%= link_to "Sign Out", destroy_user_session_path, method: :delete , id: "logo"%>
        </li>
        <li>
          <%= link_to "Share","/share",class: "button" %>
        </li>
      </ul>
    <% else %>
      <ul class="nav navbar-nav navbar-right">
        <li>
          <%= link_to "Sign Up", new_user_registration_path, class: "button", id: "logo" %>
        </li>
        <li>
         <%= link_to "Sign in", new_user_session_path , id: "logo"%>
        </li>
      </ul>
    <% end %>
  </div>
</nav>
  <p class="notice">
    <%= notice %>
  </p>
  <p class="alert">
    <%= alert %>
  </p>
  <div class="wrapper">
    <%= yield %>
  </div>
  
  <!--<div id="sidebar">

		<ul>
			<li class="category">Website</li>
			
		</ul>

		<ul>
			<li class="category">Social</li>
			<li><a href="https://twitter.com/mackenziechild">Twitter</a></li>
			<li><a href="http://instagram.com/mackenziechild">Instagram</a></li>
			<li><a href="https://github.com/mackenziechild">Github</a></li>
			<li><a href="mailto:hey@mackenziechild.me">Email</a></li>
		</ul>

	</div>
  
</body>-->
  
  
 
  <!--<script>
      $().ready(function() {
                $('#wrapper').tubular({videoId: 'ko8zeaXbB1Y'}); // where idOfYourVideo is the YouTube ID.
        });
      </script>-->
</html>

app/views/posts/_form.html.erb
<div class="container" style="background:white;padding:50px">
  
  <h1 style="color:red;font-weight:bold">Add/Edit Inspiration</h1>
<%= simple_form_for @post do |f| %>
  <%= f.input :image %>
<br>
  <%= f.input :title %>
<br>
  <%= f.input :link %>
<br>
  <%= f.input :description %>
<br>
  <%= f.button :submit %>
<br>
<% end %>
</div>

app/views/posts/edit.html.erb
<%= render 'form' %>

app/views/posts/index.html.erb
<%= link_to href: '' do %>
<%= image_tag 'http://www.bestgifever.com/data/images/2014/09/8mjh7i8.gif',:align=> "center", height:250,width:250,id: "drg"%>
<% end %>

<% if user_signed_in? %>
<!--section-start-->
  
    <div id="intro" class="jumbortron" style="color:white;font-size:40px"><b> Hello <%= current_user.name %></b></div>
    <div id="intro" class="jumbortron" style="color:white;font-size:40px"><b> Welcome to <span>Inspire</span></b></div>
    <br/>
    <h2 style="text-align:center">
      Share your inspiration and see what's inspiring others.
    </h2>
 
<% else %>
  <p id="intro">
    <h3 style="text-align:center">What's your tag?<h3>
    
    <h2 style="text-align:center">
      Share your inspiration and see what's inspiring others.
    <h2>
  </p>
<% end %>
      <!--section end-->
<div style="padding:150px;bottom:100px" id="posts">
  <% @posts.each do |post| %>
    <div class="post">
      <div class="post_image">
        <%= link_to (image_tag post.image.url(:small)), post %>
      </div>
      <div class="post_content">
        <div class="title">
          <h2>
            <%= link_to post.title, post %>
          </h2>
        </div>
        <div class="data clearfix">
          <p class="username">
            Shared by
            <%= post.user.name %>
          </p>
          <p class="buttons">
            <span>
              <i class="fa fa-comments-o"></i>
              <%= post.comments.count %>
            </span>
            <span>
              <i class="fa fa-thumbs-o-up"></i>
              <%= post.get_likes.size %>
            </span>
          </p>
        </div>
      </div>
    </div>
  <% end %>
</div>
      <div>
      <% form_tag posts_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  <p>
    <% end %>
      </div>
      
      <div style="top:50px">
      <iframe width='1500px' height='300' frameBorder='1' src='https://a.tiles.mapbox.com/v4/neeraj512.lnn57n5e/attribution,zoompan,zoomwheel,geocoder,share.html?access_token=pk.eyJ1IjoibmVlcmFqNTEyIiwiYSI6ImRiWlBua0UifQ.aTrnZr5s5d5jteg1uci4AA'></iframe></div>
      <script>
      $().ready(function() {
                $('#wrapper').tubular({videoId: 'aZwev9_Y58A'}); // where idOfYourVideo is the YouTube ID.
        });
      </script>

app/views/posts/new.html.erb
<%= render 'form' %>

app/views/posts/show.html.erb
<!--<div class="area">
 inspire
</div>-->
 
    <script src="http://code.jquery.com/ui/1.9.1/jquery-ui.js"></script>
    
    <script src="https://cdnjs.cloudflare.com/ajax/libs/handlebars.js/3.0.1/handlebars.min.js"></script>


 
   <section style="background:white;padding-right:100px;padding-top:50px;padding-left:50px;padding-bottom:1500px">

  <div style="padding-left:950px;postion:absolute;text-align:center">
    <p><b>Check what Spotify has got for you!</b></p>
  </div>
    <div style="left:1200px;position:absolute" class="col-md-4.5" id="results"></div>
     <script id="results-template" type="text/x-handlebars-template">
    {{#each albums.items}}
    <div style="background-image:url({{images.0.url}})" data-album-id="{{id}}" class="cover">
    <a href="{{external_urls.spotify}}">
       </a>
       </div>
    {{/each}}
</script>
     <script>
     // Find the template id and display results of a particular Tag / Title
var templateSource = document.getElementById('results-template').innerHTML,
    template = Handlebars.compile(templateSource),
    resultsPlaceholder = document.getElementById('results'),
    playingCssClass = 'playing',
    audioObject = null;

var fetchTracks = function (albumId, callback) {
    $.ajax({
        url: 'https://api.spotify.com/v1/albums/' + albumId,
        success: function (response) {
            callback(response);
        }
    });
};

var searchAlbums = function (query) {
    $.ajax({
        url: 'https://api.spotify.com/v1/search',
        data: {
            q: 'artist:' + query,
            type: 'album',
            market: "US"
        },
        success: function (response) {
            resultsPlaceholder.innerHTML = template(response);
        }
    });
};

results.addEventListener('click', function(e) {
    var target = e.target;
    if (target !== null && target.classList.contains('cover')) {
        if (target.classList.contains(playingCssClass)) {
            audioObject.pause();
        } else {
            if (audioObject) {
                audioObject.pause();
            }
            fetchTracks(target.getAttribute('data-album-id'), function(data) {            
                audioObject = new Audio(data.tracks.items[0].preview_url);
                audioObject.play();
                target.classList.add(playingCssClass);
                audioObject.addEventListener('ended', function() {
                    target.classList.remove(playingCssClass);
                });
                audioObject.addEventListener('pause', function() {
                    target.classList.remove(playingCssClass);
               });
            });
        }
    }
});
$( document ).ready(function(){
	
			var val1= $("#string").text();
			searchAlbums(val1);
	
});
     </script>
 
<div id="post_show" >
  <label id="string">
    <h1><%= @post.title %></h1>
  </label>
  <p class="username">
    Shared by
    <%= @post.user.name %>
    about
    <%= time_ago_in_words(@post.created_at) %>
    
  </p>
  
  <div class="clearfix">
    <div class="post_image_description">
      <%= image_tag @post.image.url(:medium) %>
      <div class="description">
        <%= simple_format(@post.description) %>
      </div>
    </div>
    <div class="post_data">
      <%= link_to "Visit Link", @post.link, class: "button" %>
      <%= link_to like_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-up"></i>
        <%= pluralize(@post.get_upvotes.size, "Like") %>
      <% end %>
      <%= link_to dislike_post_path(@post), method: :get, class: "data" do %>
        <i class="fa fa-thumbs-o-down"></i>
        <%= pluralize(@post.get_downvotes.size, "Dislike") %>
      <% end %>
      <p class="data">
        <i class="fa fa-comments-o"></i>
        <%= pluralize(@post.comments.count, "Comment") %>
      </p>
      <% if @post.user == current_user %>
        <%= link_to "Edit", edit_post_path(@post), class: "data" %>
        <%= link_to "Delete", post_path(@post), method: :delete, data: { confirm: "Are you sure?" }, class: "data" %>
      <% end %>
    </div>
    
  </div>


<div id="comments">
  <h2 class="comment_count">
    <%= pluralize(@post.comments.count, "Comment") %>
  </h2>
  <% @comments.each do |comment| %>
    <div class="comment">
      <p class="username">
        <%= comment.user.name %>
      </p>
      <p class="content">
        <%= comment.content %>
      </p>
    </div>
  <% end %>
  <%= render "comments/form" %>
</div>
  
     </div>
    
<!--<div id="tabs">
    <ul>
        <li>            <a href="#a">Billboard Top Charts</a>        </li> 
        <li>            <a href="#b">Europe Top Charts</a>        </li>
        <li>            <a href="#c">USA Top Charts</a>        </li>
        
    </ul>
    <div id="a">    <div class="container">    <ul class="youtube-video-gallery1">    </ul>    </div>    </div>
    <div id="b">    <div class="container">    <ul class="youtube-video-gallery2">    </ul>    </div>    </div>
    <div id="c">    <div class="container">    <ul class="youtube-video-gallery3">    </ul>    </div>    </div>
</div>-->
      <div style="postion:absolute" class="col-lg-6" id="youtube-video-gallery1"> </div>
  
   <script>
      $(document).ready(function(){var val1= $("#string").text();  
          $("#youtube-video-gallery1").youtubeVideoGallery({
            
            apiFallbackUrl: 'https://www.youtube.com/results?search_query=Digital+Life',
              apiUrl: 'https://gdata.youtube.com/feeds/api/videos?q='+ val1 +'&orderby=viewCount&start-index=1&alt=json&max-results=30&v=2&fullscreen=1'
          });
      });
    // $('#tabs')
   // .tabs()
    //.addClass('ui-tabs-vertical ui-helper-clearfix');
  </script>
    
 <div  id="connect">
    <button class="btn btn-primary" id="btn-connect">Connect with twitter</button>
</div>
<div style="left 100px" class="col-md-8"id="res">
   <!-- <div class="input-group">
        <input type="text" class="form-control" value="#" id="search" />
       <span class="input-group-btn">
            <button class="btn btn-primary" type="button" id="btn-search">Search</button>
        </span>
    </div>-->
    <div id="search-res"></div>
</div>

<script id="entry-template" type="text/x-handlebars-template">
    <ul id="timeline">
    {{#each statuses}}
        <li>
            <img class="thumbnail" src="{{user.profile_image_url}}" />
            <span class="content">
                <span class="author">{{user.name}}</span>
                <span class="text">{{link text}}</span>
            </span>
        </li>
    {{/each}}
    </ul>
</script>

<script>

  $('#btn-connect').click(function() {
    //Initialize the SDK with my OAuth.io public key, then display the OAuth authorization form
    OAuth.initialize('ONf48m1EPSpKthdy0RLG801bJz4')
    OAuth.popup('twitter',function(err,twitter) {
        //hide the connect and show the search form
        $('#connect').slideUp('fast')
        $('#res').slideDown('fast')
        
        //when click on the search button, make the search on Twitter and display the result
        $(document).ready(function() {
            var search = $('#string').text()
            twitter.get('/1.1/search/tweets.json?q=' + search).done(function(data) {
                var template = Handlebars.compile($('#entry-template').html())
                var content = template({
                    statuses: data.statuses
                })
                $('#search-res').html(content)
            })
        })
        $('#btn-search').click()
    })
})

//replace URL by html link
Handlebars.registerHelper('link', function(text)  {
    var exp = /((https?|ftp|file):\/\/[-A-Z0-9+&@#\/%?=~_|!:,.;]*[-A-Z0-9+&@#\/%=~_|])/ig
    var exp2 = /(@[A-Za-z0-9]+)/ig
    return new Handlebars.SafeString(text.replace(exp,'<a href="$1">$1</a>').replace())
})
     </script>  
     
   </section>

app/views/songs/delete.html.erb
<h1>Songs#delete</h1>
<p>Find me in app/views/songs/delete.html.erb</p>

app/views/songs/index.html.erb
<div class="container" id="share" style="background:#FFFFFF;bottom:10px">
<!--<h2 style="color:red;">Share your tracks and upload them to S3</h2>-->
  <img style="display: block;margin-left: auto;margin-right: auto " src='http://assets.rappler.com/612F469A6EA84F6BAE882D2B94A4B421/img/402066C85613444B9602EB0FC677C5D1/amazon-web-services-down-20140527.gif'></img>


   <%= form_tag upload_path, :method => "post", :multipart => true do %>
    <%= file_field_tag "mp3file" %>
<br>
    <%= submit_tag "Upload" %>

<% end %>
<br>

<h2>Download and Delete Existing MP3's</h2>
 <table id="table" style="padding:500px">
    <thead>
<tr>
<th>Rank</th>
<th>Country</th>
<th>US $</th>
<th>Year</th>
</tr>
</thead>
   </td> <div style="display: block;margin-left: auto;margin-right: auto " id="audio"> 
</div> <br>
<% @songs.each do |song| %>
 
    <tr>
        <td><%= song.key %></td>
      <td><%= link_to image_tag("http://danabands.dreamhtml.com/wp-content/themes/danabands/images/play-icon.png"), download_url_for(song.key), :class => "html5" %>
      <td><%= link_to image_tag("http://upload.wikimedia.org/wikipedia/commons/e/e3/Ppbc_icon_download.png"), download_url_for(song.key) %></td>
      <td><%= link_to image_tag("http://www.paychessentry.com/images/icons/delete-icon.png"),  "songs/delete/?song=" + song.key, :confirm => 'Are you sure you want to delete ' + song.key + '?' %></td>
   
   </tr>
 
<% end %>
   
    </table>
 
</div>
<script>
  $(document).ready(function() {
    var audioSection = $('#audio');
    $('#table').dynatable();
    $('a.html5').click(function() {
 
        var audio = $('<audio>', {
             controls : 'controls'
        });
 
        var url = $(this).attr('href');
        $('<source>').attr('src', url).appendTo(audio);
        audioSection.html(audio);
        return false;
    });
});
</script>

app/views/songs/upload.html.erb
<h1>Songs#upload</h1>
<p>Find me in app/views/songs/upload.html.erb</p>